### PR TITLE
Updates from recently using archetype

### PR DESCRIPTION
**Pull request by klucar**
Added slf4j and ninja.leaping.configurate dependencies to pom.
Moved o.s.a.settings.config to o.s.a.config in MyPlugin class.

### CODE REVIEW

**Comment by stephan-gh** [comment]
The dependencies should come automatically as transitive dependencies from the SpongeAPI dependency, shouldn't they?

**Comment by gabizou** [comment]
They very well should, I'm not sure why this is even necessary when transitive dependencies do change every now and then.

**Comment by zml2008** [comment]
yeah, those dependencies should not be in the pom.

**Comment by klucar** [comment]
I updated the PR. You guys are correct that you don't need those explicitly, it was just my IDE complaining. (IDEA fwiw) The config service.config change was still needed.

**Comment by zml2008** [comment]
This has been fixed with the recent batch of changes.

**Pull request closed without merging**
